INSERT INTO dojos (name, created_at, updated_at) VALUES ('Denver', now(),now());
INSERT INTO dojos (name, created_at, updated_at) VALUES ('Cleveland', now(),now());
INSERT INTO dojos (name, created_at, updated_at) VALUES ('Vegas', now(),now());
DELETE FROM dojos WHERE dojos.id = 7;
DELETE FROM dojos WHERE dojos.id = 8;
DELETE FROM dojos WHERE dojos.id = 9;
INSERT INTO dojos (name, created_at, updated_at) VALUES ('Global', now(),now());
INSERT INTO dojos (name, created_at, updated_at) VALUES ('Vinland', now(),now());
INSERT INTO dojos (name, created_at, updated_at) VALUES ('Space', now(),now());
INSERT INTO ninjas (first_name, last_name, created_at, updated_at, dojo_id) VALUES ('Hank','Hill', now(),now(), 1);
INSERT INTO ninjas (first_name, last_name, created_at, updated_at, dojo_id) VALUES ('Stank','Hill', now(),now(), 1);
INSERT INTO ninjas (first_name, last_name, created_at, updated_at, dojo_id) VALUES ('Blank','Hill', now(),now(), 1);
INSERT INTO ninjas (first_name, last_name, created_at, updated_at, dojo_id) VALUES ('Big','Bob', now(),now(), 2);
INSERT INTO ninjas (first_name, last_name, created_at, updated_at, dojo_id) VALUES ('Small','Bill', now(),now(), 2);
INSERT INTO ninjas (first_name, last_name, created_at, updated_at, dojo_id) VALUES ('Medium','Mark', now(),now(), 2);
INSERT INTO ninjas (first_name, last_name, created_at, updated_at, dojo_id) VALUES ('Hank','Hill', now(),now(), 3);
INSERT INTO ninjas (first_name, last_name, created_at, updated_at, dojo_id) VALUES ('Stank','Hill', now(),now(), 3);
INSERT INTO ninjas (first_name, last_name, created_at, updated_at, dojo_id) VALUES ('Blank','Hill', now(),now(), 3);
SELECT * FROM ninjas WHERE dojo_id = 1;
SELECT * FROM ninjas WHERE dojo_id = 3;
SELECT name FROM dojo WHERE ninja.dojo_id = 3;
